/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CreateRouteImport } from './routes/create'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as BasketIdRouteImport } from './routes/basket.$id'
import { Route as CreatorIdRouteImport } from './routes/creator.$id'
import { Route as ResearchIdRouteImport } from './routes/research.$id'
import { Route as ApiPortfolioWalletRouteImport } from './routes/api/portfolio.$wallet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const BasketIdRoute = BasketIdRouteImport.update({
  id: '/basket/$id',
  path: '/basket/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorIdRoute = CreatorIdRouteImport.update({
  id: '/creator/$id',
  path: '/creator/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIdRoute = ResearchIdRouteImport.update({
  id: '/research/$id',
  path: '/research/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortfolioWalletRoute = ApiPortfolioWalletRouteImport.update({
  id: '/api/portfolio/$wallet',
  path: '/api/portfolio/$wallet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/create': typeof CreateRoute
  '/discover': typeof DiscoverRoute
  '/portfolio': typeof PortfolioRoute
  '/saved': typeof SavedRoute
  '/basket/$id': typeof BasketIdRoute
  '/creator/$id': typeof CreatorIdRoute
  '/research/$id': typeof ResearchIdRoute
  '/api/portfolio/$wallet': typeof ApiPortfolioWalletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/create': typeof CreateRoute
  '/discover': typeof DiscoverRoute
  '/portfolio': typeof PortfolioRoute
  '/saved': typeof SavedRoute
  '/basket/$id': typeof BasketIdRoute
  '/creator/$id': typeof CreatorIdRoute
  '/research/$id': typeof ResearchIdRoute
  '/api/portfolio/$wallet': typeof ApiPortfolioWalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/create': typeof CreateRoute
  '/discover': typeof DiscoverRoute
  '/portfolio': typeof PortfolioRoute
  '/saved': typeof SavedRoute
  '/basket/$id': typeof BasketIdRoute
  '/creator/$id': typeof CreatorIdRoute
  '/research/$id': typeof ResearchIdRoute
  '/api/portfolio/$wallet': typeof ApiPortfolioWalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/create'
    | '/discover'
    | '/portfolio'
    | '/saved'
    | '/basket/$id'
    | '/creator/$id'
    | '/research/$id'
    | '/api/portfolio/$wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/create'
    | '/discover'
    | '/portfolio'
    | '/saved'
    | '/basket/$id'
    | '/creator/$id'
    | '/research/$id'
    | '/api/portfolio/$wallet'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/create'
    | '/discover'
    | '/portfolio'
    | '/saved'
    | '/basket/$id'
    | '/creator/$id'
    | '/research/$id'
    | '/api/portfolio/$wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  CreateRoute: typeof CreateRoute
  DiscoverRoute: typeof DiscoverRoute
  PortfolioRoute: typeof PortfolioRoute
  SavedRoute: typeof SavedRoute
  BasketIdRoute: typeof BasketIdRoute
  CreatorIdRoute: typeof CreatorIdRoute
  ResearchIdRoute: typeof ResearchIdRoute
  ApiPortfolioWalletRoute: typeof ApiPortfolioWalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basket/$id': {
      id: '/basket/$id'
      path: '/basket/$id'
      fullPath: '/basket/$id'
      preLoaderRoute: typeof BasketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/$id': {
      id: '/creator/$id'
      path: '/creator/$id'
      fullPath: '/creator/$id'
      preLoaderRoute: typeof CreatorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/$id': {
      id: '/research/$id'
      path: '/research/$id'
      fullPath: '/research/$id'
      preLoaderRoute: typeof ResearchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portfolio/$wallet': {
      id: '/api/portfolio/$wallet'
      path: '/api/portfolio/$wallet'
      fullPath: '/api/portfolio/$wallet'
      preLoaderRoute: typeof ApiPortfolioWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  CreateRoute: CreateRoute,
  DiscoverRoute: DiscoverRoute,
  PortfolioRoute: PortfolioRoute,
  SavedRoute: SavedRoute,
  BasketIdRoute: BasketIdRoute,
  CreatorIdRoute: CreatorIdRoute,
  ResearchIdRoute: ResearchIdRoute,
  ApiPortfolioWalletRoute: ApiPortfolioWalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
